# Generated by Django 5.2.7 on 2026-08-21 05:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StorefrontLayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم")),
                (
                    "is_global_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="مفعّل عام"
                    ),
                ),
                (
                    "active_start_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="يبدأ في"),
                ),
                (
                    "active_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ينتهي في"
                    ),
                ),
                (
                    "active_days",
                    models.JSONField(
                        blank=True, default=list, verbose_name="أيام التفعيل"
                    ),
                ),
                (
                    "active_start_hour",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ساعة البداية"
                    ),
                ),
                (
                    "active_end_hour",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ساعة النهاية"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تخطيط المتجر",
                "verbose_name_plural": "تخطيطات المتجر",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("carousel", "سلايدر متحرك"),
                            ("text_block", "كتلة نصية"),
                            ("image", "صورة"),
                            ("product_list", "قائمة منتجات"),
                            ("collection_showcase", "عرض مجموعة"),
                            ("category_list", "قائمة تصنيفات"),
                            ("photo_link_grid", "شبكة صور بروابط"),
                            ("hero_cta", "بانر رئيسي تفاعلي"),
                            ("announcement_bar", "شريط الإعلانات"),
                            ("spacer", "فاصل مساحي"),
                            ("recently_viewed", "شوهدت مؤخراً"),
                            ("buy_again", "إعادة شراء"),
                            ("recommended_for_you", "موصى به لك"),
                            ("trending_near_you", "رائج في منطقتك"),
                        ],
                        max_length=32,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="البيانات"),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="الترتيب"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "style",
                    models.JSONField(blank=True, null=True, verbose_name="النمط"),
                ),
                (
                    "targeting",
                    models.JSONField(blank=True, null=True, verbose_name="الاستهداف"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="storefront.storefrontlayout",
                        verbose_name="التخطيط",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر",
                "verbose_name_plural": "عناصر الواجهة",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
