import { db } from '@/lib/db/drizzle';
import { collections, productToCollection, products } from '@/lib/db/schema';
import {
  InsertCollection,
  SelectCollection,
  UpdateCollection,
  ManageProductsInCollection,
  RemoveProductsFromCollection,
} from '../types/collectionTypes';
import { and, eq, inArray, desc, sql, asc } from 'drizzle-orm';

export const collectionService = {
  // Create a new collection
  async createCollection(data: InsertCollection): Promise<SelectCollection> {
    // ID is generated by the database (uuid defaultRandom())
    const [newCollection] = await db
      .insert(collections)
      .values(data)
      .returning();
    if (!newCollection) {
      throw new Error("فشل إنشاء المجموعة");
    }
    return newCollection;
  },

  // Get a single collection by its ID
  async getCollectionById(id: string): Promise<SelectCollection | null> {
    const [collection] = await db
      .select({
        id: collections.id,
        name: collections.name,
        slug: collections.slug,
        description: collections.description,
        isActive: collections.isActive,
        createdAt: collections.createdAt,
        updatedAt: collections.updatedAt,
      })
      .from(collections)
      .where(eq(collections.id, id));
    return collection || null;
  },

  // Get a single collection by its slug
  async getCollectionBySlug(slug: string): Promise<SelectCollection | null> {
    const [collection] = await db
      .select({
        id: collections.id,
        name: collections.name,
        slug: collections.slug,
        description: collections.description,
        isActive: collections.isActive,
        createdAt: collections.createdAt,
        updatedAt: collections.updatedAt,
      })
      .from(collections)
      .where(eq(collections.slug, slug));
    return collection || null;
  },

  // Get all collections
  async getAllCollections(options?: {
    page?: number;
    limit?: number;
    orderBy?: keyof SelectCollection;
    order?: 'asc' | 'desc';
    search?: string; // Added search parameter
  }): Promise<{ collections: (SelectCollection & { products: { productId: string }[] })[]; total: number }> {
    const { page = 1, limit = 10, orderBy = 'createdAt', order = 'desc', search } = options || {};
    const offset = (page - 1) * limit;

    const orderByColumn = collections[orderBy as keyof typeof collections.$inferSelect] || collections.createdAt;

    const conditions = [];
    if (search) {
      conditions.push(sql`(${collections.name} ILIKE ${`%${search}%`} OR ${collections.slug} ILIKE ${`%${search}%`} OR ${collections.description} ILIKE ${`%${search}%`})`);
    }
    const whereCondition = conditions.length > 0 ? and(...conditions) : undefined;

    const collectionsQuery = db
      .select({
        id: collections.id,
        name: collections.name,
        slug: collections.slug,
        description: collections.description,
        isActive: collections.isActive,
        createdAt: collections.createdAt,
        updatedAt: collections.updatedAt,
      })
      .from(collections)
      .where(whereCondition)
      .limit(limit)
      .offset(offset)
      .orderBy(
        order === 'asc'
          ? asc(orderByColumn)
          : desc(orderByColumn)
      );

    const totalQuery = db
      .select({ count: sql<number>`count(*)` })
      .from(collections)
      .where(whereCondition);

    const [fetchedCollections, totalResult] = await Promise.all([
      collectionsQuery,
      totalQuery,
    ]);
    const total = totalResult[0]?.count ? Number(totalResult[0].count) : 0;

    // Fetch all product assignments for these collections
    const collectionIds = fetchedCollections.map(c => c.id);
    let allAssignments: { collectionId: string; productId: string; name?: string }[] = [];
    if (collectionIds.length > 0) {
      allAssignments = await db
        .select({
          collectionId: productToCollection.collectionId,
          productId: productToCollection.productId,
          name: products.name,
        })
        .from(productToCollection)
        .innerJoin(products, eq(products.id, productToCollection.productId))
        .where(inArray(productToCollection.collectionId, collectionIds));
    }
    // Map assignments to each collection
    const collectionsWithProducts = fetchedCollections.map(col => ({
      ...col,
      products: allAssignments
        .filter(a => a.collectionId === col.id)
        .map(a => ({ productId: a.productId, name: a.name })),
    }));
    return { collections: collectionsWithProducts, total };
  },

  // Update an existing collection
  async updateCollection(
    id: string,
    data: Partial<Omit<UpdateCollection, 'id'>> // data no longer contains imageUrl
  ): Promise<SelectCollection | null> {
    const [updatedCollection] = await db
      .update(collections)
      .set({ ...data, updatedAt: new Date() })
      .where(eq(collections.id, id))
      .returning({
        id: collections.id,
        name: collections.name,
        slug: collections.slug,
        description: collections.description,
        isActive: collections.isActive,
        createdAt: collections.createdAt,
        updatedAt: collections.updatedAt,
      });
    return updatedCollection || null;
  },

  // Delete a collection
  async deleteCollection(id: string): Promise<boolean> {
    // First, remove all product associations for this collection
    await db
      .delete(productToCollection)
      .where(eq(productToCollection.collectionId, id));

    // Then, delete the collection itself
    const result = await db.delete(collections).where(eq(collections.id, id));
    return result.rowCount !== null && result.rowCount > 0; // Handle possible null for rowCount
  },

  // Add multiple products to a collection
  async addProductsToCollection(
    data: ManageProductsInCollection
  ): Promise<void> {
    const { collectionId, productIds } = data;
    if (productIds.length === 0) {
      return;
    }
    const valuesToInsert = productIds.map((productId) => ({
      collectionId,
      productId,
    }));
    await db.insert(productToCollection).values(valuesToInsert).onConflictDoNothing(); // Or handle conflicts as needed
  },

  // Remove multiple products from a collection
  async removeProductsFromCollection(
    data: RemoveProductsFromCollection
  ): Promise<void> {
    const { collectionId, productIds } = data;
    if (productIds.length === 0) {
      return;
    }
    await db
      .delete(productToCollection)
      .where(
        and(
          eq(productToCollection.collectionId, collectionId),
          inArray(productToCollection.productId, productIds)
        )
      );
  },

  // Get all products belonging to a specific collection
  async getProductsByCollectionId(
    collectionId: string,
    options?: { page?: number; limit?: number }
  ): Promise<{ products: any[]; total: number }> { // Replace any[] with SelectProduct[] or similar
    const { page = 1, limit = 10 } = options || {};
    const offset = (page - 1) * limit;

    const productRelations = await db
      .select({
        productId: productToCollection.productId,
      })
      .from(productToCollection)
      .where(eq(productToCollection.collectionId, collectionId))
      .groupBy(productToCollection.productId)
      .limit(limit)
      .offset(offset);

    if (productRelations.length === 0) {
      return { products: [], total: 0 };
    }

    const productIds = productRelations.map(pr => pr.productId);

    const fetchedProducts = await db
      .select() // Select all columns from products table
      .from(products)
      .where(inArray(products.id, productIds));
      
    const totalQuery = await db
      .select({ count: sql<number>`count(*)` })
      .from(productToCollection)
      .where(eq(productToCollection.collectionId, collectionId));

    // Cast to your actual product type, e.g., fetchedProducts as SelectProduct[]
    return { products: fetchedProducts as any[], total: totalQuery[0]?.count || 0 }; // Replace any[]
  },
};

// Helper for orderBy in getAllCollections if not directly mapping
// This might be overly complex if SelectCollection keys match table columns directly
// For now, direct mapping is used.
// const getSortableColumn = (orderBy: keyof SelectCollection) => {
//   const mapping: Record<keyof SelectCollection, any> = {
//     id: collections.id,
//     name: collections.name,
//     slug: collections.slug,
//     description: collections.description,
//     imageUrl: collections.imageUrl,
//     isActive: collections.isActive,
//     createdAt: collections.createdAt,
//     updatedAt: collections.updatedAt,
//   };
//   return mapping[orderBy] || collections.createdAt;
// };
