# Generated by Django 5.2.7 on 2026-08-21 04:18

import apps.core.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False, verbose_name="تم التحقق من الهاتف"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="الاسم"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default=None,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "عميل"),
                            ("staff", "موظف"),
                            ("manager", "مشرف"),
                            ("admin", "مدير"),
                            ("owner", "مالك"),
                        ],
                        default="customer",
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("is_staff", models.BooleanField(default=False, verbose_name="موظف")),
                ("banned", models.BooleanField(default=False, verbose_name="محظور")),
                ("ban_reason", models.TextField(blank=True, verbose_name="سبب الحظر")),
                (
                    "ban_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ينتهي الحظر في"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True,
                        default=None,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", apps.core.models.UserManager()),
            ],
        ),
    ]
