# Generated by Django 5.2.7 on 2026-08-23 20:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pg_trgm_extension"),
        ("orders", "0006_cart_customer_name_cart_is_recovered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lifetime_spend",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="إجمالي المشتريات (د.ل)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="loyalty_points",
            field=models.PositiveIntegerField(default=0, verbose_name="نقاط الولاء"),
        ),
        migrations.AddField(
            model_name="user",
            name="vip_tier",
            field=models.CharField(
                choices=[
                    ("SILVER", "المستوى الفضي"),
                    ("GOLD", "المستوى الذهبي"),
                    ("DIAMOND", "المستوى الماسي"),
                ],
                default="SILVER",
                max_length=20,
                verbose_name="مستوى VIP",
            ),
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("points_change", models.IntegerField(verbose_name="تغير النقاط")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ORDER_EARNED", "اكتساب من طلب"),
                            ("REVIEW_BONUS", "مكافأة تقييم موثق"),
                            ("CHECKOUT_REDEEMED", "خصم عند الشراء"),
                            ("MANUAL_ADJUSTMENT", "تعديل يدوي"),
                        ],
                        max_length=30,
                        verbose_name="نوع الحركة",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="الوصف")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_transactions",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة نقاط ولاء",
                "verbose_name_plural": "سجل حركات الولاء",
                "ordering": ["-created_at"],
            },
        ),
    ]
