# Generated by Django 5.2.7 on 2026-08-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_user_lifetime_spend_user_loyalty_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cod_blacklist_reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="سبب حظر الدفع عند الاستلام"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cod_rejections_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="عدد مرات رفض طلبات COD"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_cod_blacklisted",
            field=models.BooleanField(
                default=False, verbose_name="محظور من الدفع عند الاستلام"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "عميل"),
                    ("support", "خدمة العملاء"),
                    ("staff", "موظف"),
                    ("manager", "مشرف"),
                    ("admin", "مدير"),
                    ("owner", "مالك"),
                ],
                default="customer",
                max_length=20,
                verbose_name="الدور",
            ),
        ),
    ]
