# Generated by Django 5.2.7 on 2026-09-27 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_populate_libyan_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=120, verbose_name='اسم المصرف')),
                ('branch', models.CharField(blank=True, max_length=120, verbose_name='الفرع')),
                ('account_holder', models.CharField(max_length=200, verbose_name='اسم المستفيد')),
                ('account_number', models.CharField(max_length=40, verbose_name='رقم الحساب')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='الآيبان')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'حساب مصرفي',
                'verbose_name_plural': 'الحسابات المصرفية',
                'ordering': ['sort_order', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='نسائم ليبيا', max_length=120, verbose_name='اسم المتجر')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم القانوني')),
                ('legal_name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم القانوني (إنجليزي)')),
                ('cr_number', models.CharField(blank=True, max_length=50, verbose_name='رقم السجل التجاري')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('site_url', models.URLField(default='https://nasaeem.ly', verbose_name='رابط الموقع')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف خدمة العملاء')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='رقم واتساب')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('bank_transfer_note', models.TextField(blank=True, verbose_name='ملاحظة التحويل المصرفي')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
            },
        ),
    ]
