# Generated by Django 5.2.7 on 2026-08-23 19:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0004_cartpromotion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseHub",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("TRIPOLI_MAIN", "مخزن طرابلس الرئيسي والمنطقة الغربية"),
                            (
                                "BENGHAZI_REGIONAL",
                                "مخزن بنغازي الإقليمي والمنطقة الشرقية",
                            ),
                            ("MISRATA_CENTRAL", "مخزن مصراتة والوسطى"),
                            ("SOUTH_SEBHA", "مخزن سبها والمنطقة الجنوبية"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="رمز المخزن",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=150, verbose_name="اسم المخزن بالعربية"
                    ),
                ),
                (
                    "city_coverage",
                    models.JSONField(
                        default=list,
                        help_text="قائمة بأسماء المدن الليبية التابعة للمخزن",
                        verbose_name="المدن المغطاة",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="العنوان والموقع"
                    ),
                ),
                (
                    "manager_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="هاتف المشرف / المسؤول"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="مفعل للخدمة"),
                ),
            ],
            options={
                "verbose_name": "مركز توزيع مخزني",
                "verbose_name_plural": "مراكز التوزيع المخزنية",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CODReconciliationStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statement_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="رقم الكشف",
                    ),
                ),
                (
                    "courier_code",
                    models.CharField(max_length=50, verbose_name="رمز شركة الشحن"),
                ),
                (
                    "courier_name",
                    models.CharField(max_length=150, verbose_name="اسم شركة الشحن"),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="بداية الفترة"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="نهاية الفترة"
                    ),
                ),
                (
                    "total_orders_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي الشحنات بالكشف"
                    ),
                ),
                (
                    "matched_orders_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد الشحنات المتطابقة"
                    ),
                ),
                (
                    "discrepancies_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد الفروقات والملاحظات"
                    ),
                ),
                (
                    "total_collected_expected",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="إجمالي المطلوب تحصيله",
                    ),
                ),
                (
                    "total_collected_actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="إجمالي المحصل الفعلي",
                    ),
                ),
                (
                    "total_delivery_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="إجمالي عمولات التوصيل",
                    ),
                ),
                (
                    "net_bank_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="صافي الإيداع البنكي",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة تحت المراجعة"),
                            ("committed", "معتمدة ومرحّلة مالياً"),
                            ("rejected", "مرفوضة"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="حالة المطابقة",
                    ),
                ),
                (
                    "operator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_cod_statements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموظف المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "كشف مطابقة تحصيل COD",
                "verbose_name_plural": "كشوفات مطابقة تحصيل COD",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CODReconciliationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tracking_number",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="رقم التتبع"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="رقم الطلب",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="اسم المستلم"
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="المبلغ المسجل بالنظام",
                    ),
                ),
                (
                    "collected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="المبلغ المحصل فعلياً",
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="عمولة التوصيل",
                    ),
                ),
                (
                    "discrepancy_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="فارق المبلغ",
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("matched", "مطابق 100%"),
                            ("amount_mismatch", "فارق في مبلغ التحصيل"),
                            ("order_not_found", "الطلب غير موجود بالنظام"),
                            ("already_settled", "تمت تسويته مسبقاً"),
                        ],
                        default="matched",
                        max_length=30,
                        verbose_name="حالة التطابق",
                    ),
                ),
                (
                    "status_note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ملاحظة التدقيق"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="معتمد للتسوية"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliation_items",
                        to="orders.order",
                        verbose_name="الطلب المتطابق",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="delivery.codreconciliationstatement",
                        verbose_name="كشف المطابقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند كشف مطابقة",
                "verbose_name_plural": "بنود كشف المطابقة",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CourierTrackingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courier_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="رمز شركة التوصيل"
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        choices=[
                            ("SHIPMENT_CREATED", "تم إنشاء الشحنة"),
                            ("PICKED_UP", "تم استلام الشحنة من المستودع"),
                            ("IN_TRANSIT", "في الطريق بين مراكز الفرز"),
                            ("OUT_FOR_DELIVERY", "مع المندوب - جاري التوصيل"),
                            ("DELIVERED", "تم التسليم بنجاح للعميل"),
                            ("DELIVERY_FAILED", "تعذر التوصيل / تأجيل"),
                            ("RETURNED", "مرتجع إلى مستودع المتجر"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="رمز الحالة",
                    ),
                ),
                (
                    "status_label_ar",
                    models.CharField(
                        max_length=255, verbose_name="وصف الحالة بالعربية"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="الموقع الحالي"
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="اسم السائق / المندوب"
                    ),
                ),
                (
                    "driver_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="هاتف السائق"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات إضافية")),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="بيانات الـ Webhook الخام",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(verbose_name="تاريخ ووقت حدوث الحركة"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة تتبع شحنة",
                "verbose_name_plural": "حركات تتبع الشحنات",
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppVerificationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_phone",
                    models.CharField(max_length=50, verbose_name="هاتف العميل"),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="رمز التحقق الآمن",
                    ),
                ),
                (
                    "gps_lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="خط العرض (Latitude)"
                    ),
                ),
                (
                    "gps_lng",
                    models.FloatField(
                        blank=True, null=True, verbose_name="خط الطول (Longitude)"
                    ),
                ),
                (
                    "gps_address_text",
                    models.TextField(
                        blank=True, verbose_name="العنوان المحدث من العميل"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار رد العميل"),
                            ("confirmed", "تم التأكيد من العميل بنجاح"),
                            ("address_updated", "تم تحديث العنوان والـ GPS"),
                            ("expired", "منتهي الصلاحية"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="حالة التأكيد",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_session",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة تأكيد واتساب",
                "verbose_name_plural": "جلسات تأكيد الواتساب",
                "ordering": ["-created_at"],
            },
        ),
    ]
