# Generated by Django 5.2.7 on 2026-08-21 05:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="رمز الطريقة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("completed", "مكتمل"),
                            ("failed", "فشل"),
                            ("cancelled", "ملغي"),
                            ("refunded", "مسترجع"),
                            ("waiting_for_verification", "بانتظار التحقق"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ"
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="المرجع"
                    ),
                ),
                (
                    "provider_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات المزوّد"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التحقق"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة",
                "verbose_name_plural": "الدفعات",
                "ordering": ["-created_at"],
            },
        ),
    ]
