# Generated by Django 5.2.7 on 2026-08-23 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_cartpromotion"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="رمز الحساب",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="اسم الحساب")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "أصول"),
                            ("liability", "التزامات"),
                            ("equity", "حقوق ملكية"),
                            ("revenue", "إيرادات"),
                            ("expense", "مصروفات"),
                        ],
                        max_length=32,
                        verbose_name="نوع الحساب",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الرصيد الحالي",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "حساب مالي",
                "verbose_name_plural": "شجرة الحسابات المالية",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="نوع المرجع"
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="معرّف المرجع",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="البيان / الوصف"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "قيد محاسبي",
                "verbose_name_plural": "دفتر القيود المحاسبية",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("debit", "مدين"), ("credit", "دائن")],
                        max_length=16,
                        verbose_name="نوع القيد",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="payments.ledgeraccount",
                        verbose_name="الحساب",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="payments.ledgertransaction",
                        verbose_name="القيد المحاسبي",
                    ),
                ),
            ],
            options={
                "verbose_name": "طرف القيد",
                "verbose_name_plural": "أطراف القيود المحاسبية",
            },
        ),
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="مبلغ الاسترداد"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="سبب الاسترداد"
                    ),
                ),
                (
                    "provider_refund_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="مرجع الاسترداد لدى البوابة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المعالجة"),
                            ("completed", "مكتمل بنجاح"),
                            ("failed", "فشل الاسترداد"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="حالة الاسترداد",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاكتمال"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموظف المنفذ",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_refunds",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                        verbose_name="الدفعة الأصلية",
                    ),
                ),
            ],
            options={
                "verbose_name": "استرداد مالي",
                "verbose_name_plural": "الاستردادات المالية",
                "ordering": ["-created_at"],
            },
        ),
    ]
