# Generated by Django 5.2.7 on 2026-08-21 05:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0002_city_region_useraddress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="الاسم"),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="الرمز"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="الإعدادات"
                    ),
                ),
            ],
            options={
                "verbose_name": "طريقة توصيل",
                "verbose_name_plural": "طرق التوصيل",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethodConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method_code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="رمز الطريقة",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="الاسم المعروض"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "config_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="الإعدادات"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="مفعّل"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "إعداد طريقة دفع",
                "verbose_name_plural": "إعدادات طرق الدفع",
                "ordering": ["sort_order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="معرّف الجلسة",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="تنتهي في"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سلة",
                "verbose_name_plural": "السلات",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=1, verbose_name="الكمية")),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.cart",
                        verbose_name="السلة",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_items",
                        to="catalog.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_items",
                        to="catalog.productvariant",
                        verbose_name="الخيار",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر سلة",
                "verbose_name_plural": "عناصر السلة",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="الرمز",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "type",
                    models.CharField(
                        choices=[("percentage", "نسبة مئوية"), ("fixed", "مبلغ ثابت")],
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="القيمة",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="النسبة",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="تاريخ البداية",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="تاريخ النهاية",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="الحد الأدنى للطلب",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="الحد الأقصى للخصم",
                    ),
                ),
                (
                    "usage_limit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="حد الاستخدام"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="عدد الاستخدامات"),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discounts",
                        to="catalog.product",
                        verbose_name="المنتجات",
                    ),
                ),
            ],
            options={
                "verbose_name": "خصم",
                "verbose_name_plural": "الخصومات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="رقم الطلب",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("processing", "قيد المعالجة"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغي"),
                            ("refunded", "مسترجع"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "shipping_status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("accepted", "تم القبول"),
                            ("delivered", "تم التوصيل"),
                            ("returned", "مرتجع"),
                            ("cancelled", "ملغي"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="حالة الشحن",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="المجموع الفرعي",
                    ),
                ),
                (
                    "discount_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="إجمالي الخصم",
                    ),
                ),
                (
                    "shipping_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="إجمالي الشحن",
                    ),
                ),
                (
                    "delivery_discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="خصم التوصيل",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الإجمالي",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="طريقة الدفع"
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(blank=True, verbose_name="عنوان الشحن"),
                ),
                (
                    "billing_address",
                    models.TextField(blank=True, verbose_name="عنوان الفوترة"),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات العميل"),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم التتبع"
                    ),
                ),
                (
                    "tracking_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="رابط التتبع"
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="المرجع"
                    ),
                ),
                (
                    "delivery_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="orders.deliverymethod",
                        verbose_name="طريقة التوصيل",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="orders.discount",
                        verbose_name="الخصم",
                    ),
                ),
                (
                    "shipping_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="core.city",
                        verbose_name="مدينة الشحن",
                    ),
                ),
                (
                    "shipping_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="core.region",
                        verbose_name="منطقة الشحن",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب",
                "verbose_name_plural": "الطلبات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=1, verbose_name="الكمية")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الإجمالي"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="اسم المنتج"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.productvariant",
                        verbose_name="الخيار",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر طلب",
                "verbose_name_plural": "عناصر الطلب",
                "ordering": ["created_at"],
            },
        ),
    ]
