# Generated by Django 5.2.7 on 2026-08-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_number_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="finalised_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت التأكيد"
            ),
        ),
    ]
