# Generated by Django 5.2.7 on 2026-08-23 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_finalised_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartPromotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        default="توصيل مجاني",
                        max_length=150,
                        verbose_name="عنوان العرض",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        default="أضف {remaining} د.ل للحصول على توصيل مجاني!",
                        max_length=255,
                        verbose_name="نص التشجيع",
                    ),
                ),
                (
                    "success_message",
                    models.CharField(
                        default="تهانينا! لقد حصلت على توصيل مجاني لكافة المدن 🚀",
                        max_length=255,
                        verbose_name="رسالة النجاح",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=200.0,
                        max_digits=10,
                        verbose_name="الحد الأدنى للطلب",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="مفعّل"
                    ),
                ),
            ],
            options={
                "verbose_name": "عرض السلة والشحن المجاني",
                "verbose_name_plural": "عروض السلة والشحن المجاني",
                "ordering": ["-created_at"],
            },
        ),
    ]
