# Generated by Django 5.2.7 on 2026-08-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_cartpromotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gift_message",
            field=models.TextField(
                blank=True, default="", verbose_name="نص رسالة كرت الإهداء"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="gift_recipient_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="اسم المُهدى إليه (إلى)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="gift_sender_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="اسم المُهدي (من)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="gift_wrap_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="رسوم التغليف الإضافية",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="gift_wrap_type",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="نوع التغليف"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="hide_invoice_prices",
            field=models.BooleanField(
                default=False, verbose_name="إخفاء الأسعار من الفاتورة"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_gift",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="طلب إهداء فاخر"
            ),
        ),
    ]
