# Generated by Django 5.2.7 on 2026-08-23 20:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_gift_message_order_gift_recipient_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="customer_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="اسم العميل"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="is_recovered",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="تم استرجاعها"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                verbose_name="رقم الهاتف للمتابعة",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="recovery_discount_code",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="كود الخصم الممنوح"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="recovery_sms_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ إرسال تذكير الاسترجاع"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="loyalty_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="خصم نقاط الولاء (د.ل)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="loyalty_points_earned",
            field=models.PositiveIntegerField(
                default=0, verbose_name="نقاط مكتسبة من الطلب"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="loyalty_points_redeemed",
            field=models.PositiveIntegerField(
                default=0, verbose_name="نقاط مستبدلة في الطلب"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vip_tier_at_order",
            field=models.CharField(
                default="SILVER", max_length=20, verbose_name="مستوى VIP وقت الطلب"
            ),
        ),
    ]
