# Generated by Django 5.2.7 on 2026-08-21 05:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="الاسم"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="المعرّف",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعة",
                "verbose_name_plural": "المجموعات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="الاسم"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="المعرّف",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="السعر",
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="السعر قبل الخصم",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="رمز المنتج",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الباركود"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "has_variants",
                    models.BooleanField(default=False, verbose_name="يحتوي على خيارات"),
                ),
                (
                    "track_quantity",
                    models.BooleanField(default=False, verbose_name="تتبّع الكمية"),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="المخزون")),
                (
                    "reserved_stock",
                    models.IntegerField(default=0, verbose_name="المخزون المحجوز"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="وصف SEO"),
                ),
                (
                    "width",
                    models.IntegerField(blank=True, null=True, verbose_name="العرض"),
                ),
                (
                    "length",
                    models.IntegerField(blank=True, null=True, verbose_name="الطول"),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="الارتفاع"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="الوزن",
                    ),
                ),
            ],
            options={
                "verbose_name": "منتج",
                "verbose_name_plural": "المنتجات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VariantOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="اسم الخيار")),
            ],
            options={
                "verbose_name": "خيار",
                "verbose_name_plural": "الخيارات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="الاسم"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="المعرّف",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "image_url",
                    models.CharField(blank=True, max_length=255, verbose_name="الصورة"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="تصنيف نظامي"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="التصنيف الأب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصنيف",
                "verbose_name_plural": "التصنيفات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصنيف منتج",
                "verbose_name_plural": "تصنيفات المنتجات",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="catalog.ProductCategory",
                to="catalog.category",
            ),
        ),
        migrations.CreateModel(
            name="ProductCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.collection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعة منتج",
                "verbose_name_plural": "مجموعات المنتجات",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="collections",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="catalog.ProductCollection",
                to="catalog.collection",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=255, verbose_name="الرابط")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="النص البديل"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة منتج",
                "verbose_name_plural": "صور المنتجات",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="رمز المنتج",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="السعر",
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="السعر قبل الخصم",
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="المخزون")),
                (
                    "reserved_stock",
                    models.IntegerField(default=0, verbose_name="المخزون المحجوز"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "خيار منتج",
                "verbose_name_plural": "خيارات المنتجات",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("change", models.IntegerField(verbose_name="التغيير")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual", "تعديل يدوي"),
                            ("sale", "بيع"),
                            ("reservation", "حجز"),
                            ("release", "إلغاء حجز"),
                            ("restock", "إعادة تخزين"),
                            ("return", "مرتجع"),
                            ("correction", "تصحيح"),
                        ],
                        max_length=32,
                        verbose_name="السبب",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="ملاحظة")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_logs",
                        to="catalog.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_logs",
                        to="catalog.productvariant",
                        verbose_name="الخيار",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل مخزون",
                "verbose_name_plural": "سجلات المخزون",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VariantValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=100, verbose_name="القيمة")),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalog.variantoption",
                        verbose_name="الخيار",
                    ),
                ),
            ],
            options={
                "verbose_name": "قيمة خيار",
                "verbose_name_plural": "قيم الخيارات",
                "ordering": ["option__name", "value"],
            },
        ),
        migrations.AddField(
            model_name="productvariant",
            name="values",
            field=models.ManyToManyField(
                blank=True,
                related_name="variants",
                to="catalog.variantvalue",
                verbose_name="القيم",
            ),
        ),
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(
                fields=("product", "category"), name="unique_product_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="productcollection",
            constraint=models.UniqueConstraint(
                fields=("product", "collection"), name="unique_product_collection"
            ),
        ),
    ]
