# Generated by Django 5.2.7 on 2026-08-23 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_wishlistitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfumeAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fragrance_family",
                    models.CharField(
                        default="شرقي فاخر",
                        max_length=100,
                        verbose_name="العائلة العطرية",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MEN", "رجالي"),
                            ("WOMEN", "نسائي"),
                            ("UNISEX", "للجنسين"),
                        ],
                        default="UNISEX",
                        max_length=20,
                        verbose_name="الفئة المستهدفة",
                    ),
                ),
                (
                    "concentration",
                    models.CharField(
                        default="Eau de Parfum",
                        max_length=50,
                        verbose_name="التركيز العطري",
                    ),
                ),
                (
                    "origin_country",
                    models.CharField(
                        default="فرنسا",
                        max_length=100,
                        verbose_name="بلد المنشأ والتصنيع",
                    ),
                ),
                (
                    "top_notes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="قمة العطر (Top Notes)"
                    ),
                ),
                (
                    "heart_notes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="قلب العطر (Heart Notes)"
                    ),
                ),
                (
                    "base_notes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="قاعدة العطر (Base Notes)",
                    ),
                ),
                (
                    "longevity_score",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="مؤشر الثبات والدوام"
                    ),
                ),
                (
                    "longevity_hours",
                    models.CharField(
                        default="14 إلى 18 ساعة",
                        max_length=50,
                        verbose_name="مدة الثبات التقريبية",
                    ),
                ),
                (
                    "sillage_score",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="مؤشر الفوحان والانتشار"
                    ),
                ),
                (
                    "seasons",
                    models.JSONField(
                        blank=True, default=list, verbose_name="فصول الاستخدام المثالية"
                    ),
                ),
                (
                    "occasions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="المناسبات المقترحة"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfume_details",
                        to="catalog.product",
                        verbose_name="المنتج العطري",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل وبيانات العطر الحسية",
                "verbose_name_plural": "تفاصيل العطور الحسية",
            },
        ),
    ]
