# Generated by Django 5.2.7 on 2026-08-23 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_perfumeattribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="اسم الحزمة")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=200,
                        unique=True,
                        verbose_name="الرمز اللطيف",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الحزمة وميزاتها"),
                ),
                (
                    "bundle_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="سعر الحزمة المخفض (د.ل)",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="السعر الأصلي قبل الخصم (د.ل)",
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        default="وفر حتى 20%",
                        max_length=100,
                        verbose_name="شارة التوفير",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="مفعل ومعروض"
                    ),
                ),
                (
                    "included_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bundles_included_in",
                        to="catalog.product",
                        verbose_name="المنتجات المشمولة في الحزمة",
                    ),
                ),
                (
                    "main_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles_as_main",
                        to="catalog.product",
                        verbose_name="المنتج الأساسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "حزمة عطور وتوفير",
                "verbose_name_plural": "حزم العطور والتوفير",
                "ordering": ["-created_at"],
            },
        ),
    ]
