# Generated by Django 5.2.7 on 2026-08-23 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productbundle"),
        ("orders", "0006_cart_customer_name_cart_is_recovered_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(default=5, verbose_name="التقييم"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان التقييم"
                    ),
                ),
                ("comment", models.TextField(verbose_name="نص وتجربة التقييم")),
                (
                    "photo_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="رابط صورة العميل مع الزجاجة",
                    ),
                ),
                (
                    "is_verified_buyer",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="مشترٍ مؤكد"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="معتمد للنشر"
                    ),
                ),
                (
                    "points_awarded",
                    models.BooleanField(
                        default=False, verbose_name="تم منح 50 نقطة مكافأة"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="orders.order",
                        verbose_name="الطلب المرتبط",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم منتج",
                "verbose_name_plural": "تقييمات المنتجات",
                "ordering": ["-created_at"],
            },
        ),
    ]
